### ISSUE TITLE
No matter what XLSX file I upload I get the same exact java error

### ISSUE THREAD

**Issue by bubba198** [codingchili/excelastic#10]
The only way to make it work is to deliberately enter an incorrect row number for the labels. Then it uploads the file but of course the row with the field labels is incorrect so the uploaded data is no good. Here's the error:

```
Error!
Model.ParserException: org.apache.poi.POIXMLException: org.apache.poi.openxml4j.exceptions.InvalidFormatException: Package should contain a content type part [M1.13]
	at Model.FileParser.<init>(FileParser.java:39)
	at Controller.Website.parse(Website.java:84)
	at Controller.Website.lambda$null$0(Website.java:59)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:158)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:271)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.poi.POIXMLException: org.apache.poi.openxml4j.exceptions.InvalidFormatException: Package should contain a content type part [M1.13]
	at org.apache.poi.util.PackageHelper.open(PackageHelper.java:39)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:273)
	at Model.FileParser.<init>(FileParser.java:31)
	... 11 more
Caused by: org.apache.poi.openxml4j.exceptions.InvalidFormatException: Package should contain a content type part [M1.13]
	at org.apache.poi.openxml4j.opc.ZipPackage.getPartsImpl(ZipPackage.java:201)
	at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:684)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:275)
	at org.apache.poi.util.PackageHelper.open(PackageHelper.java:37)
	... 13 more
	
```

**Comment by codingchili** [comment]
Which software did you use to create the XLSX file? could you provide a file that is failing to import?

**Comment by bubba198** [comment]
[StrategicETFGrowth.xlsx](https://github.com/codingchili/parser-excel-elasticsearch/files/1085644/StrategicETFGrowth.xlsx)
Microsoft Excel 14.0.7182.5000 64bit version

**Comment by codingchili** [comment]
On the development branch snapshot-1.2 this file indexes without a problem. I will attempt to complete this as soon as possible. 

The exception indicates that the file is formatted in an unexpected format, in this version i added support for XML97 in addition to OOXML.

**Comment by codingchili** [comment]
Reopen if required.
