### ISSUE TITLE
Error: Timed out after waiting 30000(ms) for a reply

### ISSUE THREAD

**Issue by pulserdd** [codingchili/excelastic#38]
Getting the below error after partially parsing the .xls file:

Command:
`java -jar excelastic-1.2.2.jar customer-success-sf-data-xls.xls customer-success-excel metrics`

Stacktrace:
`INFO: Submitted items [6885 -> 7139] of 25359 with result [200] OK into 'customer-success-excel' [28.2%]
Aug 02, 2017 10:35:39 AM com.codingchili.ApplicationLauncher lambda$importFile$2
SEVERE: Failed to import
(TIMEOUT,-1) Timed out after waiting 30000(ms) for a reply. address: 1
SEVERE: Failed to import
(TIMEOUT,-1) Timed out after waiting 30000(ms) for a reply. address: 1
	at io.vertx.core.eventbus.impl.HandlerRegistration.sendAsyncResultFailure(HandlerRegistration.java:118)
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$new$0(HandlerRegistration.java:65)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:803)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:774)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

Aug 02, 2017 10:35:39 AM com.codingchili.Model.ElasticWriter lambda$submitForIndexing$3
INFO: Submitted items [7140 -> 7394] of 25359 with result [200] OK into 'customer-success-excel' [29.2%]`

**Comment by codingchili** [comment]
Hello, this was fixed already. Could you please try again with the 1.2.2?

This timeout should not affect the imported items, the error is triggered when the whole import process takes longer than 30 seconds.

**Comment by pulserdd** [comment]
thanks for your reply. I've been trying with 1.2.2 itself. Here's my command:

`java -jar excelastic-1.2.2.jar data.xls restored-index-2 metrics`

Please note that the xls I am importing is a big file ~25k rows (4.9mb).

**Comment by codingchili** [comment]
I updated the jar in the 1.2.2 a couple of days after uploading it. Renamed the current version to 1.2.2b, could you try to download it again?

**Comment by pulserdd** [comment]
thanks that one helped.

**Comment by pulserdd** [comment]
@codingchili is this parsing tool supposed to create 1 document in elasticsearch for every row in the excel worksheet? I have 418 rows in xls but only 96 documents in elasticsearch. Would highly appreciate your inputs. Thanks.

**Comment by codingchili** [comment]
Yes. Make sure its consistently formatted and no fields are missing. The date field is extra sensitive. If you can't find any inconsistencies in formatting I would like to have a file to reproduce the issue with.
