### ISSUE TITLE
Launching the application 

### ISSUE THREAD

**Issue by soumya-ranjan-sahoo** [codingchili/excelastic#57]
Hi Team,

I am getting the following error stack upon running the launcher.

Can some one help me provide a direction to a fix. 

Thanks in advance. 

C:\Users\ssahoo\Downloads>java -jar excelastic-1.2.6.jar run Launcher
Apr 11, 2018 4:27:01 PM com.codingchili.ApplicationLauncher <init>
INFO: Starting excelastic 1.2.6..
Apr 11, 2018 4:27:01 PM com.codingchili.ApplicationLauncher <init>
INFO: to import files without the web interface use: <filename> <index> <mapping>
Apr 11, 2018 4:27:02 PM com.codingchili.Model.ElasticWriter start
INFO: Started elastic writer. tls = false
Apr 11, 2018 4:27:02 PM com.codingchili.Controller.Website lambda$start$7
INFO: Started website on port 50510
Apr 11, 2018 4:27:02 PM com.codingchili.ApplicationLauncher lambda$new$1
INFO: Successfully started application
Apr 11, 2018 4:27:02 PM com.codingchili.ApplicationLauncher importFile
INFO: Loading file run from filesystem..
Apr 11, 2018 4:27:02 PM com.codingchili.ApplicationLauncher lambda$importFile$4
SEVERE: Failed to load file run
io.vertx.core.file.FileSystemException: java.nio.file.NoSuchFileException: run
        at io.vertx.core.file.impl.FileSystemImpl$13.perform(FileSystemImpl.java:740)
        at io.vertx.core.file.impl.FileSystemImpl$13.perform(FileSystemImpl.java:732)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:275)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.NoSuchFileException: run
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.readAllBytes(Unknown Source)
        at io.vertx.core.file.impl.FileSystemImpl$13.perform(FileSystemImpl.java:736)

**Comment by codingchili** [comment]
Hello,

If you start the application with one or more parameters it will attempt to import files from the command line. The following is the syntax to run from the commandline:
`java -Xmx1g -jar excelastic-1.2.6.jar <filename> <index> <mapping> --clear`

Where mapping and --clear are optional.

To run with the web interface, run the following in your terminal:
`java -Xmx1g -jar excelastic-1.2.6.jar`

I have updated the readme to clarify this.

Thanks for submitting an issue, let me know if it works out for you.
