### ISSUE TITLE
Mapping file (for geo_point) not being loaded

### ISSUE THREAD

**Issue by Trouble123** [codingchili/excelastic#58]
Hi
I am trying to import a file that has geo locations, and when doing so kibana doesnt show it as a geo_point type. The format looks like this - -38.182, 144.35388

Is there a way to import it as is, or do i need to use a mapping file?
I thought  mapping file is required so i created a file as follows:
{
                "mappings": {
                        "data": {
                                "properties": {
                                        "geo_point_D": {
                                                "type": "geo_point",
                                                "ignore_malformed": true
                                        },
                                        "geo_point_P": {
                                                "type": "geo_point",
                                                "ignore_malformed": true
                                        }
                                }
                        }
                }

}
And then i tried to call load the excel file and the mapping file from the UI (mapping file in same folder as jar and configuration.json) but it didnt seem to load (nothing in the jar cl showed reference to it). I then tried it using the following cli - and once again, no reference to the mapping file being loaded and doesnt seem to be using it. The file was original 100,000 records but i deleted 99750 of the lines beofre loading it)

java -Xmx1g -jar excelastic-1.2.7.jar STT2.xlsx stt3 -mapping stt_mapping.json --clear
May 10, 2018 10:44:28 PM com.codingchili.logging.ApplicationLogger startupMessage
INFO: Starting excelastic 1.2.7..
May 10, 2018 10:44:28 PM com.codingchili.logging.ApplicationLogger startupMessage
INFO: to import files without the web interface use please supply arguments for <fileName> <indexName>
May 10, 2018 10:44:28 PM com.codingchili.logging.ApplicationLogger startupMessage
INFO: optional arguments: --mapping <mappingName> --offset <number> --clear
May 10, 2018 10:44:28 PM com.codingchili.logging.ApplicationLogger onWriterStarted
INFO: Started elastic writer. tls = false
May 10, 2018 10:44:28 PM com.codingchili.Controller.Website lambda$startWebsite$2
INFO: Started website on port 8080
May 10, 2018 10:44:28 PM com.codingchili.logging.ApplicationLogger applicationStartup
INFO: Successfully started application
May 10, 2018 10:44:28 PM com.codingchili.logging.ApplicationLogger loadingFromFilesystem
INFO: Loading file STT2.xlsx from filesystem..
May 10, 2018 10:44:28 PM com.codingchili.logging.ApplicationLogger parsingStarted
INFO: Parsing excel file..
May 10, 2018 10:44:29 PM com.codingchili.logging.ApplicationLogger onWriterConnected
INFO: Connected to elasticsearch server 6.2.1 at bi.thissolution.com:9200
May 10, 2018 10:44:31 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 2295 ms, time limit is 2000
May 10, 2018 10:44:32 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 3430 ms, time limit is 2000
May 10, 2018 10:44:32 PM com.codingchili.logging.ApplicationLogger parsingFile
INFO: Parsing file 'STT2.xlsx' using titles from excel row 0..
May 10, 2018 10:44:33 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 4430 ms, time limit is 2000
May 10, 2018 10:44:34 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 5674 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
        at java.util.Vector.<init>(Vector.java:148)
        at java.util.Vector.<init>(Vector.java:157)
        at java.util.Observable.<init>(Observable.java:69)
        at org.apache.poi.ss.usermodel.DataFormatter$LocaleChangeObservable.<init>(DataFormatter.java:215)
        at org.apache.poi.ss.usermodel.DataFormatter$LocaleChangeObservable.<init>(DataFormatter.java:215)
        at org.apache.poi.ss.usermodel.DataFormatter.<init>(DataFormatter.java:228)
        at org.apache.poi.ss.usermodel.DataFormatter.<init>(DataFormatter.java:246)
        at org.apache.poi.ss.usermodel.DataFormatter.<init>(DataFormatter.java:237)
        at com.codingchili.Model.FileParser.getRow(FileParser.java:224)
        at com.codingchili.Model.FileParser.readRows(FileParser.java:152)
        at com.codingchili.Model.FileParser.assertFileParsable(FileParser.java:116)
        at com.codingchili.Controller.CommandLine.importFile(CommandLine.java:51)
        at com.codingchili.Controller.CommandLine.<init>(CommandLine.java:24)
        at com.codingchili.ApplicationLauncher.lambda$new$0(ApplicationLauncher.java:47)
        at com.codingchili.ApplicationLauncher$$Lambda$20/1483022288.handle(Unknown Source)
        at io.vertx.core.impl.CompositeFutureImpl.lambda$all$1(CompositeFutureImpl.java:49)
        at io.vertx.core.impl.CompositeFutureImpl$$Lambda$19/1359484306.handle(Unknown Source)
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:121)
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:83)
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:147)
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
        at io.vertx.core.impl.DeploymentManager.lambda$reportResult$6(DeploymentManager.java:448)
        at io.vertx.core.impl.DeploymentManager$$Lambda$51/2141558340.handle(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
        at io.vertx.core.impl.ContextImpl$$Lambda$9/1781256139.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

May 10, 2018 10:44:35 PM com.codingchili.logging.ApplicationLogger parsedFile
INFO: Parsed 99999 rows from file STT2.xlsx.
May 10, 2018 10:44:35 PM com.codingchili.logging.ApplicationLogger importStarted
INFO: File parsed, starting import to stt3..
May 10, 2018 10:44:36 PM com.codingchili.logging.ApplicationLogger onImportedBatch
INFO: Submitted items [0 -> 127] of 100000 with result [200] OK into 'stt3' [0.1%]

**Comment by codingchili** [comment]
Hello, 

Thanks for submitting an issue.

The mapping parameter/field in the UI is the name of the mapping, this is not a file reference. The mapping must be added to ES manually. 

For example: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html

Regards

**Comment by Trouble123** [comment]
Hi, are you able to give me an example of the parameter/field for geo point in the UI?

**Comment by codingchili** [comment]
Hello,

Sorry, I have not used geo point at all. 

Closing this issue,
