### ISSUE TITLE
 Failed to handleMessage. address: bus.transactions

### ISSUE THREAD

**Issue by svanschalkwyk** [codingchili/excelastic#60]
[UPDATE]
Application will not upload to ES indices with underscore ("_") in names.
Does wotk if underscores are replaced by dash ("-").
Any chance of fixing this please?
Thanks for a great app.

[UPDATE]: File read error was due to Excel file mistake on my part.
Application now succeeds, and reports 5 rows uploaded (the spreadsheet has 3 rows with #1 being the field names.
No data in ES though.

Elasticsearch 6.4.0 on Windows 8.1
Exceltastic executing on Linux Mint 18
Spreadsheet created with LibreOffice Calc 5.1.6.2

```
INFO: Parsing file 'RRD Best Bets.xlsx' using titles from excel row 0..
Aug 31, 2018 12:49:59 PM com.codingchili.logging.ApplicationLogger parsedFile
INFO: Parsed 4 rows from file RRD Best Bets.xlsx.
Aug 31, 2018 12:49:59 PM io.vertx.core.eventbus.impl.HandlerRegistration
SEVERE: Failed to handleMessage. address: bus.transactions
java.lang.ArrayIndexOutOfBoundsException: 6
	at com.codingchili.Model.FileParser.getRow(FileParser.java:253)
	at com.codingchili.Model.FileParser.readRows(FileParser.java:152)
	at com.codingchili.Model.FileParser.access$000(FileParser.java:20)
	at com.codingchili.Model.FileParser$1.request(FileParser.java:92)
	at com.codingchili.Model.ElasticWriter$1.onSubscribe(ElasticWriter.java:98)
	at com.codingchili.Model.FileParser.subscribe(FileParser.java:87)
	at com.codingchili.Model.ElasticWriter.lambda$null$0(ElasticWriter.java:60)
	at com.codingchili.Model.ElasticWriter.clearBeforeIndexing(ElasticWriter.java:182)
	at com.codingchili.Model.ElasticWriter.lambda$startSubmitListener$1(ElasticWriter.java:58)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:223)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:200)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:533)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)

Aug 31, 2018 12:49:59 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.ArrayIndexOutOfBoundsException: 6
	at com.codingchili.Model.FileParser.getRow(FileParser.java:253)
	at com.codingchili.Model.FileParser.readRows(FileParser.java:152)
	at com.codingchili.Model.FileParser.access$000(FileParser.java:20)
	at com.codingchili.Model.FileParser$1.request(FileParser.java:92)
	at com.codingchili.Model.ElasticWriter$1.onSubscribe(ElasticWriter.java:98)
	at com.codingchili.Model.FileParser.subscribe(FileParser.java:87)
	at com.codingchili.Model.ElasticWriter.lambda$null$0(ElasticWriter.java:60)
	at com.codingchili.Model.ElasticWriter.clearBeforeIndexing(ElasticWriter.java:182)
	at com.codingchili.Model.ElasticWriter.lambda$startSubmitListener$1(ElasticWriter.java:58)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:223)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:200)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:533)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by codingchili** [comment]
Hello,

These kind of issues are very hard to troubleshoot without the failing file. There are so many parameters and secret tricks that can be embedded in the files, like special formatting, ghost rows or differences between spreadsheet softares.

If you can provide the file, or a similar file with the same issues I will take a look right away. 

Thanks for submitting an issue! 😸

**Comment by codingchili** [comment]
We are not doing anything special with the index name, it should work as long as there is no limitation in ElasticSearch. Will take a look at it when I'm investigating the import issues.

**Comment by codingchili** [comment]
Closing, Please reopen if you are still having issues.
