### ISSUE TITLE
IndexoutofBoundexecption

### ISSUE THREAD

**Issue by sathyajackson** [codingchili/excelastic#64]
Hello,

Many thanks to you for deploying the new jar with enhancement... kudo :)

I used the new tool to upload my csv to kiban and I ended up with the following error after 100 % completed.

java.lang.IndexOutOfBoundsException
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:669)
	at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:265)
	at com.codingchili.Model.CSVParser.readRowCount(CSVParser.java:70)
	at com.codingchili.Model.CSVParser.setFileData(CSVParser.java:46)
	at com.codingchili.Controller.Website.lambda$parse$11(Website.java:176)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)

When i try to upload the same using api to elasticsearch, i am able to upload ( just a small chunk of data for testing ).

I am not sure, is this something you have to look for, but I am not good in java or rather can understand and turn on the switch which is causing this error.

Can you share some thoughts on the above message?

**Comment by codingchili** [comment]
Hello!

Thanks for the feedback!

Can you provide the file that fails? Content and original filename. 

I have some ideas and would like to reproduce ASAP.

Best regards

**Comment by sathyajackson** [comment]
Hi,

I don't think I will be able to share the file. The file size is huge and it's a consolidated AWS billing csv (21G).

All I am doing is uploading that file into the elasticsearch which runs on AWS (m5x.large) instance. I am using Indexing as sample-*, mapping as default ( just to test) and row as 3, then upload the file.

The actual process goes for some time (approx 4 hours) to upload the content to the elasticsearch. As soon as it reaches 60 to 70 % I get this error. Any solution to overcome this is of great help.

I am using the latest jar 1.3.1 with basic HTTP configuration on elasticsearch.

**Comment by codingchili** [comment]
Hi, 

I will generate some larger files and try to reproduce the issue.
There is a hard cap on ~16kB of data for each row.

How much data is there per row approximately?

**Comment by codingchili** [comment]
Update: Issue is reproduced.

**Comment by sathyajackson** [comment]
wow, that was quick.

Sorry that I am not able to submit what you requested. Now, what's next? any enhancement needed or just a tweak in configuration is enough?

**Comment by sathyajackson** [comment]
How much data is there per row approximately?

it's huge and it almost occupied the entire excell rows.

**Comment by codingchili** [comment]
I have found some issues with the current implementation.
We are using memory mapped files, which has a limit of 2GB per map.

So for really large files, we need to stripe a bunch of maps.
I implemented the striping but I need more time to verify and test the performance.

**Comment by codingchili** [comment]
I increased the per-row buffer to 512kB, this should be enough unless there are uncompressed images in the data. Will continue testing tomorrow.

**Comment by codingchili** [comment]
Hello, 

we should now be able to handle large CSV files more effectively and with less errors.

Released as 1.3.2.
https://github.com/codingchili/parser-excel-elasticsearch/releases

**Comment by sathyajackson** [comment]
Hey,

Now that I am ending up with a different error ColumnsExceededHeadersException.

com.codingchili.Model.ColumnsExceededHeadersException: Encountered too many values (32) on row 1, expected to match headers (31).
	at com.codingchili.Model.CSVParser.process(CSVParser.java:143)
	at com.codingchili.Model.CSVParser.readRow(CSVParser.java:203)
	at com.codingchili.Model.CSVParser.initialize(CSVParser.java:101)
	at com.codingchili.Controller.Website.lambda$parse$11(Website.java:182)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by sathyajackson** [comment]
the total file-upload size is 28GB.

**Comment by codingchili** [comment]
Aha, perfect. This should only require the first three rows of the file to reproduce.
Could you please provide the first rows of the file? At least three of them.

You can mask the data if required, as long as it still produces the error.

Thank you for your patience.

**Comment by codingchili** [comment]
If you count the number of columns on the first and second row, do they match? Any special chars such as quoted " ? We don't support escaping quotes within a quote.

"Header or value", "another, column" = OK
"Column", "column """ 2" = not supported, even though it's accepted by the rfc.

**Comment by codingchili** [comment]
I found some more issues with the implementation. We are now ignoring any CR line endings and rely on LF only, fix exists in 1.3.3 - reproduced and verified with CSV files from https://support.spatialkey.com/spatialkey-sample-csv-data/
