### ISSUE TITLE
excelastic-1.3.2  - support multiple sheets

### ISSUE THREAD

**Issue by sandytur** [codingchili/excelastic#68]
Please let me know how to upload the Excel file with multiple sheets (sheet 1, sheet 2, ...etc  ) using excelastic-1.3.2 

Means i have one excel with multiple sheets, Please help me out on this.

**Comment by codingchili** [comment]
Hello, 

Multiple sheets are not yet supported.

I added it on the roadmap, it will be included in a release in a few weeks.

Thanks for submitting an issue.

**Comment by sandytur** [comment]
Thanks for your response .....Please update me once it supports.

**Comment by sathyajackson** [comment]
Hi,

Even i need this feature to support multiple sheets

**Comment by ck-7** [comment]
We are looking forward to the multiple sheets options. 

@codingchili Thanks for the Tools which really helpful if it works for me...

cat config.json file

{
  "web_port": 9999,
  "elastic_port": 9200,
  "elastic_host": "elk-logging.XCXCXCSDSDS.com",
  "elastic_tls": true,
  "default_index": "excelastic",
  "index_lock": false,
  "authentication": true,
  "basic": "elastic:XXCXCXCXCXCCXCXCXCXCXCX"
}


**Getting blow exception while uploading** 
**ELK Version : 7.10.0** 

Dec 08, 2020 12:50:05 PM com.codingchili.Controller.Website lambda$setRouterAPI$8
INFO: Receiving uploaded file with request id 6u9x2k
Dec 08, 2020 12:50:05 PM com.codingchili.logging.ApplicationLogger parsingFile
INFO: Parsing file 'test.xlsx' using titles from row 0..
Dec 08, 2020 12:50:05 PM com.codingchili.logging.ApplicationLogger parsedFile
INFO: Parsed 14 rows from file test.xlsx.
Dec 08, 2020 12:50:05 PM io.vertx.core.eventbus.impl.HandlerRegistration
SEVERE: Failed to handleMessage. address: bus.transactions
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.codingchili.Model.ExcelParser.getRow(ExcelParser.java:251)
        at com.codingchili.Model.ExcelParser.readRows(ExcelParser.java:150)
        at com.codingchili.Model.ExcelParser.access$000(ExcelParser.java:20)
        at com.codingchili.Model.ExcelParser$1.request(ExcelParser.java:110)
        at com.codingchili.Model.ElasticWriter$1.onSubscribe(ElasticWriter.java:101)
        at com.codingchili.Model.ExcelParser.subscribe(ExcelParser.java:105)
        at com.codingchili.Model.ElasticWriter.lambda$startSubmitListener$0(ElasticWriter.java:63)
        at com.codingchili.Model.ElasticWriter.clearBeforeIndexing(ElasticWriter.java:194)
        at com.codingchili.Model.ElasticWriter.lambda$startSubmitListener$1(ElasticWriter.java:61)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:264)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:242)
        at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:565)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$5(EventBusImpl.java:524)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

Dec 08, 2020 12:50:05 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.codingchili.Model.ExcelParser.getRow(ExcelParser.java:251)
        at com.codingchili.Model.ExcelParser.readRows(ExcelParser.java:150)
        at com.codingchili.Model.ExcelParser.access$000(ExcelParser.java:20)
        at com.codingchili.Model.ExcelParser$1.request(ExcelParser.java:110)
        at com.codingchili.Model.ElasticWriter$1.onSubscribe(ElasticWriter.java:101)
        at com.codingchili.Model.ExcelParser.subscribe(ExcelParser.java:105)
        at com.codingchili.Model.ElasticWriter.lambda$startSubmitListener$0(ElasticWriter.java:63)
        at com.codingchili.Model.ElasticWriter.clearBeforeIndexing(ElasticWriter.java:194)
        at com.codingchili.Model.ElasticWriter.lambda$startSubmitListener$1(ElasticWriter.java:61)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:264)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:242)
        at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:565)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$5(EventBusImpl.java:524)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
