### ISSUE TITLE
Error when Running

### ISSUE THREAD

**Issue by DefensiveThinking** [codingchili/excelastic#74]
I get a error when running this. The CSV file is 43 megs. 

ingchili.Model.ParserException: Error at row 1831859, values (0) does not match headers (1).
	at com.codingchili.Model.CSVParser.readRow(CSVParser.java:221)
	at com.codingchili.Model.CSVParser.initialize(CSVParser.java:103)
	at com.codingchili.Controller.Website.lambda$parse$11(Website.java:193)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Not sure what I could be doing wrong. Please help

**Comment by DefensiveThinking** [comment]
Also I have a additional question: Do you think you could add a feature like add directory to where it could upload all the files into a directory?

**Comment by codingchili** [comment]
Hello, is there a newline at the end of the file? It's a special case that is probably not being handled correctly.

Yes, it's on the roadmap. 🐈

**Comment by codingchili** [comment]
Is there CR+LF or LF line endings? Do you have a file which I can reproduce the error with? 🐈

**Comment by DefensiveThinking** [comment]
Sadly I cant share the file but I think I figured out the issue. There was a blank line at the bottom of the file. Not sure why it was on that just 1 file and not the rest. I have also split the files up from 40 gig to smaller files and it seems to work much better. I look forward to your future releases.

**Comment by codingchili** [comment]
Thanks for the info, closing.
