### ISSUE TITLE
Error upload file

### ISSUE THREAD

**Issue by dfranco87** [codingchili/excelastic#75]
Hi Guys, someone helpme plz..
I followed all the steps to configuration the excelastic, i'm using a Virtual machine with CentOS 7. 
After to open the excelastic page ( java -Xmx2g -jar excelastic-1.3.4.jar) and import file, when i click on UPLOAD, the error message appear.

INFO: Receiving uploaded file with request id z0eezi
Exception in thread "vert.x-worker-thread-12" java.lang.IllegalStateException: Result is already complete: failed
        at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:101)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:279)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by codingchili** [comment]
Hi! 

Could you please provide the following
- the java version in use
- the type of file being uploaded
- the file being uploaded if possible

Does the user running the application have write permissions in the current directory? This looks more like an issue with the file upload than parsing - which suggests environment issues.

Thanks for submitting an issue!

**Comment by codingchili** [comment]
closing, please reopen if there's still issues.
