### ISSUE TITLE
SEVERE: Failed to parse file (J9+ support)

### ISSUE THREAD

**Issue by cookwjc** [codingchili/excelastic#78]
I've seen some issues with this error relating to JDK9, but that doesn't appear to be relevant here.  I've followed deployment steps documented here https://www.youtube.com/watch?v=x2KuhN1RZ4s  but always fail at file upload.

> Microsoft Windows [Version 10.0.17134.523]
> java version "1.8.0_201"
> Java(TM)
> SE Runtime Environment (build 1.8.0_201-b09)
> Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

`java.lang.NoSuchMethodError: java.nio.MappedByteBuffer.position(I)Ljava/nio/MappedByteBuffer;
        at com.codingchili.Model.CSVParser.reset(CSVParser.java:83)
        at com.codingchili.Model.CSVParser.readRowCount(CSVParser.java:110)
        at com.codingchili.Model.CSVParser.initialize(CSVParser.java:96)
        at com.codingchili.Controller.Website.lambda$parse$11(Website.java:193)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)`
I've seen

**Comment by codingchili** [comment]
Hello !

This is most likely related to issues with the Java version.

Here is another issue on the same topic: https://github.com/apache/felix/pull/114

While we work to fix this, I would suggest to try using Java 11.

Thanks a lot for submitting an issue 👍

**Comment by codingchili** [comment]
Hello @cookwjc 

I made a new release, 1.3.6.

Please let me know if you still are having issues.

BR

**Comment by cookwjc** [comment]
Thank you sir - definitely behaving better.  Current error appears to happen on CSVs. (tried multiple).  When converting the CSV to XLSX (simple open/save-as) results in a successful import. Note that the 'Error at Row' changes depending on the number of lines in the CSV. 
I've tried wrapping the header values & line values in quotes in case it was a whitespace issue.  I've tried other variations as well removing special characters, but it always fails with a variant of the following message.  
`
SEVERE: Failed to parse file '20190126.csv'.
com.codingchili.Model.ParserException: Error at row 40, values (0) does not match headers (11).
        at com.codingchili.Model.CSVParser.readRow(CSVParser.java:220)
        at com.codingchili.Model.CSVParser.initialize(CSVParser.java:102)
        at com.codingchili.Controller.Website.lambda$parse$11(Website.java:193)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)

SEVERE: Failed to parse file '20190128.csv'.
com.codingchili.Model.ColumnsHeadersMismatchException: Encountered values (11) on row 13, expected to match headers (10).
	at com.codingchili.Model.CSVParser.readRow(CSVParser.java:199)
	at com.codingchili.Model.CSVParser.initialize(CSVParser.java:102)
	at com.codingchili.Controller.Website.lambda$parse$11(Website.java:193)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by codingchili** [comment]
Could you provide me with a file that fails? Common errors are 
- CSV file ends with a newline
- the number of columns vary for some rows
- line endings not parsed correctly
- too many line breaks between rows.
- escaping quotes not supported, simple qoutes are ok.

**Comment by codingchili** [comment]
Closing due to inactivity.

Please reopen if issue persists.
