### ISSUE TITLE
ES 6.6.1 Won't Start

### ISSUE THREAD

**Issue by hackdefendr** [codingchili/excelastic#79]
I downloaded version 1.3.6 from releases.  Placed in the ES plugins folder. Changed ownership to elasticsearch. But ES won't start now.  What am I missing?

```
[2019-03-17T15:22:26,394][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [qCC9fxq] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [excelastic-1.3.6.jar]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.6.1.jar:6.6.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.6.1.jar:6.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.6.1.jar:6.6.1]
Caused by: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [excelastic-1.3.6.jar]
	at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:395) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:380) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:373) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:145) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.node.Node.<init>(Node.java:337) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.6.1.jar:6.6.1]
	... 6 more
Caused by: java.nio.file.FileSystemException: /opt/bitnami/elasticsearch/plugins/excelastic-1.3.6.jar/plugin-descriptor.properties: Not a directory
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_201-ojdkbuild]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_201-ojdkbuild]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_201-ojdkbuild]
	at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_201-ojdkbuild]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:162) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:392) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:380) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:373) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:145) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.node.Node.<init>(Node.java:337) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.6.1.jar:6.6.1]
```

**Comment by hackdefendr** [comment]
Never mind....Reading is fundamental.
