### ISSUE TITLE
TLS conf for docker

### ISSUE THREAD

**Issue by Lupanoide** [codingchili/excelastic#87]
Hello,
I would like to use excelastic in docker and connect to an elasticsearch container.  I run both on docker-compose:

```
  excelastic:
    image: codingchili/excelastic:latest
    container_name: excelastic
    volumes:
      - ./certificatissl/mytruststore.jks:/opt/excelastic/mytruststore.jks
    environment:
      - es_port=9200
      - es_host=nodo1
      - es_tls=true
      - tls=true
      - basic="admin:admin"
      - authentication=true
      - "-Djavax.net.ssl.trustStore='/opt/excelastic/mytruststore.jks'"

    ports:
      - 8080:8080
    expose:
      - "8080"
    networks:
      - esnet
    depends_on:
      - elasticsearch    
```

I have created the truststore as written and passed node pem. I don't know if my syntax to pass a trusstore argument to excelastic container is correct. The error returned is:

```
elasticsearch    | [2020-01-27T14:54:27,990][ERROR][c.a.o.s.s.h.n.OpenDistroSecuritySSLNettyHttpServerTransport] [nodo1] Exception during establishing a SSL connection: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
elasticsearch    | javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
elasticsearch    | 	at sun.security.ssl.Alert.createSSLException(Alert.java:128) ~[?:?]
elasticsearch    | 	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
elasticsearch    | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:308) ~[?:?]
elasticsearch    | 	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279) ~[?:?]
elasticsearch    | 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:181) ~[?:?]
elasticsearch    | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
elasticsearch    | 	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:672) ~[?:?]
elasticsearch    | 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:627) ~[?:?]
elasticsearch    | 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:443) ~[?:?]
elasticsearch    | 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:422) ~[?:?]
elasticsearch    | 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:634) ~[?:?]
elasticsearch    | 	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:295) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1332) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at java.lang.Thread.run(Thread.java:834) [?:?]
elasticsearch    | [2020-01-27T14:54:27,994][WARN ][o.e.h.AbstractHttpServerTransport] [nodo1] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=0.0.0.0/0.0.0.0:9200, remoteAddress=null}
elasticsearch    | io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
elasticsearch    | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at java.lang.Thread.run(Thread.java:834) [?:?]
elasticsearch    | Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
elasticsearch    | 	at sun.security.ssl.Alert.createSSLException(Alert.java:128) ~[?:?]
elasticsearch    | 	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
elasticsearch    | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:308) ~[?:?]
elasticsearch    | 	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279) ~[?:?]
elasticsearch    | 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:181) ~[?:?]
elasticsearch    | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
elasticsearch    | 	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:672) ~[?:?]
elasticsearch    | 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:627) ~[?:?]
elasticsearch    | 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:443) ~[?:?]
elasticsearch    | 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:422) ~[?:?]
elasticsearch    | 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:634) ~[?:?]
elasticsearch    | 	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:295) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1332) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
elasticsearch    | 	... 16 more

```

**Comment by codingchili** [comment]
Hello, 

It looks almost right, could you try replacing this

```
- "-Djavax.net.ssl.trustStore='/opt/excelastic/mytruststore.jks'"
```

with 

```
- java_opts="-Djavax.net.ssl.trustStore='/opt/excelastic/mytruststore.jks'"
```

Use the latest docker image, 1.3.7 - I just added support for supplying java_opts.

**Comment by codingchili** [comment]
please reopen if this is still an issue.
