### ISSUE TITLE
Thread has been blocked

### ISSUE THREAD

**Issue by RedCloudDC** [codingchili/excelastic#9]
unable to load docs your java app has this error

Mar 29, 2017 9:05:50 AM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 42027 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at Model.ElasticWriter.bulkQuery(ElasticWriter.java:50)
	at Model.ElasticWriter.lambda$processTransactions$2(ElasticWriter.java:37)
	at Model.ElasticWriter$$Lambda$25/1598655761.handle(Unknown Source)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:503)
	at io.vertx.core.eventbus.impl.EventBusImpl$$Lambda$76/402137966.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.vertx.core.impl.ContextImpl$$Lambda$24/90320863.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)

**Comment by codingchili** [comment]
When do you get this message? Is it when starting up or when importing a document? 
Which version of ElasticSearch are you using? 

Thanks for submitting an issue.

**Comment by RedCloudDC** [comment]
This happens when I import a document. I am using 5.3.0

**Comment by codingchili** [comment]
Thanks for the info, looking into it asap.

**Comment by codingchili** [comment]
Improved submission to elasticsearch to batch bulk queries in batches of 255 items. Previous behaviour attempted to insert ALL rows at once using a massive bulk query. On snapshot-1.2 branch for release soon. Submitted a file with 4095 data rows without issues in ~2 seconds.

**Comment by codingchili** [comment]
Also fixed an issue where the upload would not cancel on failure.
